2019-02-18 02:24:46,169 - app.py[line:37] - DEBUG: 查询库: 192_168_30_132_3306_fbs_fdc  SQL语句 explain select * from
2019-02-18 02:24:46,173 - app.py[line:1761] - ERROR: Exception on /rollres [POST]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../app.py", line 38, in the_test3
    res = Mysql.Mysqlconn(databases,sql)
  File "/root/huige/huige/Mysql.py", line 37, in Mysqlconn
    cursor.execute(cmd,param)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2019-02-18 02:24:46,175 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:24:46] "POST /rollres HTTP/1.1" 500 -
2019-02-18 02:33:38,133 - app.py[line:37] - DEBUG: 查询库: 192_168_30_132_3306_fbs_fdc  SQL语句 explain select * from
2019-02-18 02:33:38,137 - app.py[line:1761] - ERROR: Exception on /rollres [POST]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../app.py", line 38, in the_test3
    res = Mysql.Mysqlconn(databases,sql)
  File "/root/huige/huige/Mysql.py", line 37, in Mysqlconn
    cursor.execute(cmd,param)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2019-02-18 02:33:38,138 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:33:38] "POST /rollres HTTP/1.1" 500 -
2019-02-18 02:53:38,219 - app.py[line:37] - DEBUG: 查询库: 192_168_30_122_3306_activity  SQL语句 explain select * from cbd_shop_blacklist
2019-02-18 02:53:38,224 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:53:38] "POST /rollres HTTP/1.1" 200 -
2019-02-18 02:53:42,823 - app.py[line:37] - DEBUG: 查询库: 192_168_30_122_3306_activity  SQL语句 select * from cbd_shop_blacklist
2019-02-18 02:53:42,827 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:53:42] "POST /rollres HTTP/1.1" 200 -
2019-02-18 02:53:46,746 - app.py[line:37] - DEBUG: 查询库: 192_168_30_122_3306_db1  SQL语句 select * from cbd_shop_blacklist
2019-02-18 02:53:46,750 - app.py[line:1761] - ERROR: Exception on /rollres [POST]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../app.py", line 38, in the_test3
    res = Mysql.Mysqlconn(databases,sql)
  File "/root/huige/huige/Mysql.py", line 37, in Mysqlconn
    cursor.execute(cmd,param)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table '192_168_30_122_3306_db1.cbd_shop_blacklist' doesn't exist")
2019-02-18 02:53:46,751 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:53:46] "POST /rollres HTTP/1.1" 500 -
2019-02-18 02:53:53,319 - app.py[line:37] - DEBUG: 查询库: 192_168_30_122_3306_db1  SQL语句 select * from cbd_shop_blacklist
2019-02-18 02:53:53,323 - app.py[line:1761] - ERROR: Exception on /rollres [POST]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../app.py", line 38, in the_test3
    res = Mysql.Mysqlconn(databases,sql)
  File "/root/huige/huige/Mysql.py", line 37, in Mysqlconn
    cursor.execute(cmd,param)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table '192_168_30_122_3306_db1.cbd_shop_blacklist' doesn't exist")
2019-02-18 02:53:53,323 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:53:53] "POST /rollres HTTP/1.1" 500 -
2019-02-18 02:53:55,396 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:53:55] "GET /job HTTP/1.1" 200 -
2019-02-18 02:53:55,567 - _internal.py[line:88] - INFO: 172.10.141.102 - - [18/Feb/2019 02:53:55] "GET /all HTTP/1.1" 200 -
